spring:
  application:
    name: kicherkrabbe-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/kicherkrabbe?replicaSet=replicaset-01
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  compression:
    enabled: true
    min-response-size: 2048
