spring:
  application:
    name: kicherkrabbe-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/kicherkrabbe?replicaSet=rs0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
